title: Clasificador de imagenes
description: Clasificando imagenes de alimentos usando deep learning
about:


  Esto es un clasificador de imagenes usando Deep Learning aplicando Pytorch.




code: https://github.com/kbueso/proyecto_final_grupo_5

sampleImages:
  - name: chicken wings
    url: https://img.freepik.com/free-photo/concept-indian-cuisine-baked-chicken-wings-legs-honey-mustard-sauce-serving-dishes-restaurant-black-plate-indian-spices-wooden-table-background-image_127425-18.jpg?size=626&ext=jpg
  - name: sushi
    url: https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg
  - name: waffles
    url: https://www.simplyrecipes.com/thmb/WlGCyH0uqvvlcgEOHd0s3Q0elE4=/2000x1429/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2016__09__Buttermilk-Waffles-horiz-a-2000-44a7abeb997c4b549d92576c3043bac7.jpg
  - name: eggplant (no en datos de entramiento)
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/1280px-Solanum_melongena_24_08_2012_%281%29.JPG
  - name: mesa (no en entrenado ni tampoco es alimento)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 
